services:
  postgres:
    image: postgres:16-alpine

    restart: unless-stopped
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: insta
    ports:
      - "5732:5432"
